version: '3.8'
services:
  angular-frontend:
    build: 
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./laravel-backend:/var/www
      - ./laravel-backend/.docker/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-backend
    networks:
      - app-network

  laravel-backend:
    build: 
      context: ./laravel-backend
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: GestionEscolar
      DB_USERNAME: daniel
      DB_PASSWORD: daniel
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: GestionEscolar
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: daniel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
